---
title: "Imputation_missForest"
author: "Xinyi Lin"
date: "7/30/2019"
output:
  pdf_document: default
  html_document: default
---

```{r}
# problem
# 1. whether educate_r = 1 means student?
# 2. SEScat means?
# 3. How to deal with 98?
```


```{r, message=FALSE}
library(tidyverse)
library(missForest)
```

## Import data

```{r}
library(haven)
training <- read_dta("training.dta")
```

## Creat the variable

Notation:

Variable name: student_r

Created from: occup1_r, occup2_r

Label: student_r — yes-is a student, no-not a student, NA-occup1_r and occup2_r are NAs

```{r}
student_data = training %>%
  as_data_frame() %>%
  mutate(student_r = ifelse(occup1_r == 8 | occup2_r == 8, "yes", "no"),
         student_r = ifelse(is.na(student_r) & occup1_r == 20, "no", student_r))
head(student_data,10)
```

```{r}
# for sexp1yr > 92, make them as NAs
impu_data = student_data %>% 
  filter(ageyrs_r <= 19) %>% 
  mutate(student_r = as.factor(student_r),
         visit = as.factor(visit),
         sex = ifelse(female==1, "female", "male")) %>% 
  select(ageyrs_r, sex, student_r, area, educate_r, currmarr_r, sexp1yr, SEScat) %>% 
  mutate(sex = as.factor(sex),
         area = as.factor(area),
         educate_r = as.factor(educate_r),
         currmarr_r = as.factor(currmarr_r),
         sexp1yr = ifelse(sexp1yr > 92, NA, sexp1yr),  
         SEScat = as.factor(SEScat))
head(impu_data)
```

```{r}
summary(impu_data)
summary(impu_data$sexp1yr)
```

According to table above, there are 6208 missing values in `student_r` variables.

# Imputation

```{r}
# need to first change dataset into matrix, then change it into data frame
# how to decide parameters? cross-validation?
impu_data = as.data.frame(impu_data)
set.seed(123)
impu_forest = missForest(impu_data, variablewise = TRUE)
```

```{r}
impu_forest$OOBerror
```

