---
title: "Multiple Imputation"
author: "Xinyi Lin"
date: "7/16/2019"
output:
  pdf_document: default
  html_document: default
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(missForest)
library(Hmisc)
library(mice)
```

## Import data

```{r}
library(haven)
training <- read_dta("training.dta")
```

## Creat the variable

Notation:

Variable name: student_r

Created from: occup1_r, occup2_r

Label: student_r — yes-is a student, no-not a student, NA-occup1_r and occup2_r are NAs

```{r}
student_data = training %>%
  as_data_frame() %>%
  mutate(student_r = ifelse(occup1_r == 8 | occup2_r == 8, "yes", "no"),
         student_r = ifelse(is.na(student_r) & occup1_r == 20, "no", student_r))
head(student_data,10)
```

```{r}
impu_data = student_data %>% 
  filter(ageyrs_r <= 19) %>% 
  mutate(student_r = as.factor(student_r),
         visit = as.factor(visit),
         sex = ifelse(female==1, "female", "male")) %>% 
  select(visit, ageyrs_r, sex, occup1_r, occup2_r, student_r)
head(impu_data)
```

```{r}
md.pattern(impu_data, plot = F)
```

According to table above, there are 6208 missing values in `student_r` variables.

# Imputation

# MICE

```{r}
mice_data = mice(impu_data,seed = 123)
summary(mice_data)
mice_data$imp$student_r
```

